### ISSUE TITLE
Peer Testing Report

### ISSUE THREAD

**Issue by shepkeira** [shepkeira/LIMS#112]
Based on your findings from the peer testing session, write up a report with the following information and submit it before the deadline:

(10%) Brief description of your system and its current set of features available in the testing session

(10%) Identify the number of participants that completed your study. In particular, include a table of participant's name, status (completed, partially completed, no show, type of evaluation (user vs. thinkaloud)). For incomplete and no show statuses, provide an explanation. Indicate who ran each session and who the participant was. (only for those that run the sessions remote) Links to all the videos that were recorded.

(15%) The user group and associated list of tasks (use cases) you asked your participants to complete

(20%) List of issues discovered, prioritized and presented in order of high, medium, then low.

(20%) Average the quantitative scores you received from the participants in a bar graph with the 5 points on the y-axis and the 10 heuristics on the x-axis. Label your axes. Indicate the number of data points used in the graph. Be sure to explain the graph using the issues identified and any quoted comments you obtained from the participants.

Submit the report in PDF format

Make sure to include the links to our peer testing videos

**Comment by sayo96825** [comment]
Here is the link for the report.
https://docs.google.com/document/d/1O7zufArTHi0JUmvZOketfHt46VQcPm1hEN6ImleRZYs/edit?usp=sharing

I will go over it again still and it is also in our google drive folder.
