### ISSUE TITLE
Review Testing Guide

### ISSUE THREAD

**Issue by shepkeira** [shepkeira/LIMS#135]
- Review testing guide created by Will in #134

**Comment by shepkeira** [comment]
To confirm:
- baker.make create an instance of a model to use in the test. You only have to specify the attributes you need, everything else is random
- baker.prepare creates a reference object, but not an object to interact with directly
- recipes allow you to create multiple instances of a model with the same attributes, to be used in different tests
- Recipe: define the model and the attributes
- bake.make_recipe(recipe, attribute definition) creates an instance of the model with defined attributes (used with foreign keys)
- recipe.make() create an instance of the model where all the attributes are defined

**Comment by sselin-co** [comment]
Reviewed!

**Comment by Rock-it-science** [comment]
> To confirm:
> 
> * baker.make create an instance of a model to use in the test. You only have to specify the attributes you need, everything else is random

👍 

> * baker.prepare creates a reference object, but not an object to interact with directly

I haven't had to use this one yet, but I believe prepare() creates a non-persisted object. So you can use it like a normal object, it just won't be persisted in the database.

> * recipes allow you to create multiple instances of a model with the same attributes, to be used in different tests
> * Recipe: define the model and the attributes
> * bake.make_recipe(recipe, attribute definition) creates an instance of the model with defined attributes (used with foreign keys)

The key with recipes is that the recipe can define attributes, which is particularly useful for foreign keys as you mentioned (remember recipes can be passed as attributes!), however you don't have define all or even any attributes in a recipe, and all non-defined attributes will be filled with random data each time the recipe is instantiated/"made".

> * recipe.make() create an instance of the model where all the attributes are defined

Remember that you don't have to define any attributes when you call make(). All attributes that are not defined in the recipe will be filled with random data.

**Comment by sayo96825** [comment]
I reviewed.
