### ISSUE TITLE
Restrict which user groups have access to pages

### ISSUE THREAD

**Issue by Rock-it-science** [shepkeira/LIMS#149]
Currently, any user type can visit almost any page. We should restrict this not only for security, but also because it will raise exceptions.

**Comment by sselin-co** [comment]
I think this will tie in nicely with https://github.com/shepkeira/LIMS/issues/144, since we can leverage Django level permissions to block off content instead of relying only on template tags.

**Comment by Rock-it-science** [comment]
Oh that's true, I didn't see that issue. I'll close this one since its kind of a duplicate
