### ISSUE TITLE
LaboratoryOrders models invalid object name

### ISSUE THREAD

**Issue by Rock-it-science** [shepkeira/LIMS#170]
When accessing any of the LaboratoryOrders models on the admin dashboard, a similar error to below is returned.
![image](https://user-images.githubusercontent.com/11603490/150733018-6d376506-bc83-4146-a8cf-c87291ae0501.png)

The same error is also returned when viewing the orders results page.

**Comment by sselin-co** [comment]
I took a peek into the database and the list of tables does not contain any tables in the syntax we'd expect for laboratoryOrders

![image](https://user-images.githubusercontent.com/39775792/150897064-44926133-c3fa-4881-a9f7-1de825461773.png)

**Comment by sselin-co** [comment]
Huh, not entirely sure what changed but I suddenly am able to access the models. No idea why it would apparently resolve itself
![image](https://user-images.githubusercontent.com/39775792/150909919-36e43dfb-431f-44d8-ad9c-fae01955cbb7.png)
