### ISSUE TITLE
Report: Include an updated test report

### ISSUE THREAD

**Issue by shepkeira** [shepkeira/LIMS#305]
- Include an updated test report
- Probably ask Gema what exactly she means by this? Is it just our coverage report?

**Comment by Rock-it-science** [comment]
Messaged Gema about expectations for this.

**Comment by Rock-it-science** [comment]
From Gema's response:
For the updated test report, just include what has changed from peer testing 2 till now in terms of the testing.

For example:

* what issues found in the peer testing have been addressed and what have not been addressed,
* the new list of prioritization tasks,
* what activities your team have done some in addition to the peer testing to (within your team or with the client) to test the system,
* what is the final coverage percentage of your source code,
* etc.
